version: '3.9'
services:
    ibot-gpt:
        image: 'slendymilky/ibot-modo:latest'
        container_name: ibot-modo
        restart: always
        environment:
            - stack.env
        volumes:
            - bot_db:/iBot-Modo/database

volumes:
  bot_db: {}
